version: '3.7'
 
# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: TodoApp 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    depends_on:
      - couchbase # This service depends on mysql. Start that first.
    environment:
     COUCHBASE_CONNECTION: couchbase:11210
    networks: 
      - backend
      - frontend
 
  # Frontend Service 
  app-client:
    build:
      context: TodoAppAngular/todoApp 
      dockerfile: Dockerfile
    
    ports:
      - "8081:80" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  
 
  couchbase:
    build: ./couchbase
    image: moakbal/couchbase
    ports:
     - 8091:8091
     - 8092:8092
     - 8093:8093
     - 11210:11210
    networks:
      - backend  
    volumes:
      - couchbase-data:/opt/couchbase/var  
   
# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
  frontend: 
   
volumes:
  couchbase-data:
  
  
